
import React from 'react';
import { useData } from '../contexts/DataContext';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Icons } from '../components/ui/Icons';
import { Badge } from '../components/ui/Badge';
import { useToast } from '../contexts/ToastContext';

export const Reports: React.FC = () => {
  const { data, deleteReport, generateReport } = useData();
  const { addToast } = useToast();

  const handleGenerate = (type: 'pdf' | 'csv') => {
    generateReport(type);
    addToast(`Generating ${type.toUpperCase()} report...`, 'info');
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Reports</h1>
          <p className="text-slate-500 dark:text-slate-400">Generate and download system audits.</p>
        </div>
        <div className="flex space-x-2">
          <Button variant="secondary" onClick={() => handleGenerate('csv')}>
            <Icons.FileText className="h-4 w-4 mr-2" />
            Export CSV
          </Button>
          <Button onClick={() => handleGenerate('pdf')}>
            <Icons.Download className="h-4 w-4 mr-2" />
            Generate PDF
          </Button>
        </div>
      </div>

      <Card noPadding>
        <table className="w-full text-sm text-left">
          <thead className="text-xs text-slate-500 uppercase bg-slate-50 dark:bg-slate-800/50 dark:text-slate-400">
            <tr>
              <th className="px-6 py-3">Report Name</th>
              <th className="px-6 py-3">Type</th>
              <th className="px-6 py-3">Date Created</th>
              <th className="px-6 py-3">Generated By</th>
              <th className="px-6 py-3">Status</th>
              <th className="px-6 py-3 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-200 dark:divide-slate-700">
            {data.reports.map(report => (
              <tr key={report.id} className="bg-white dark:bg-slate-800">
                <td className="px-6 py-4 font-medium text-slate-900 dark:text-white">
                  <div className="flex items-center">
                    <Icons.FileText className="h-4 w-4 mr-2 text-slate-400" />
                    {report.title}
                  </div>
                </td>
                <td className="px-6 py-4 uppercase text-xs font-bold text-slate-500">{report.type}</td>
                <td className="px-6 py-4 text-slate-500 dark:text-slate-400">{new Date(report.date).toLocaleString()}</td>
                <td className="px-6 py-4 text-slate-500 dark:text-slate-400">{report.generatedBy}</td>
                <td className="px-6 py-4">
                  <Badge variant={report.status === 'ready' ? 'success' : report.status === 'generating' ? 'warning' : 'error'}>
                    {report.status.toUpperCase()}
                  </Badge>
                </td>
                <td className="px-6 py-4 text-right space-x-2">
                  {report.status === 'ready' && (
                    <button className="text-primary-600 hover:text-primary-700 transition-colors">
                      <Icons.Download className="h-4 w-4" />
                    </button>
                  )}
                  <button onClick={() => deleteReport(report.id)} className="text-slate-400 hover:text-red-600 transition-colors">
                    <Icons.Trash className="h-4 w-4" />
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </Card>
    </div>
  );
};
